version: "3.9"
services:
  mongo:
    container_name: db
    image: mongo:latest
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: alex
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ../mongo_data:/data/db
  go:
    container_name: webserver
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MONGO_URI: mongodb://alex:${MONGO_PASSWORD}@db:27017
    ports: 
      - 8000:8000
